#!/bin/sh
# this file should be located here: /etc/initramfs-tools/hooks/growroot-tools
PREREQ=""

prereqs() {
  echo "$PREREQ"
}

case "$1" in
  prereqs)
    prereqs
    exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /usr/bin/growpart
copy_exec /sbin/resize2fs
copy_exec /usr/sbin/sgdisk
copy_exec /sbin/partprobe
