#!/bin/sh
# this file will be deployed at /etc/initramfs-tools/scripts/local-bottom/growroot

PREREQ=""

prereqs() {
  echo "$PREREQ"
}

case "$1" in
  prereqs)
    prereqs
    exit 0
    ;;
esac


echo "[growroot] script started" > /dev/kmsg

# Fix GPT header
/usr/sbin/sgdisk -e /dev/xvda > /dev/kmsg 2>&1
echo "[growroot] sgdisk exit code=$?" > /dev/kmsg

# Force kernel to reread partition table
/sbin/partprobe /dev/xvda > /dev/kmsg 2>&1
sleep 2

# Grow partition 2
/usr/bin/growpart /dev/xvda 2 > /dev/kmsg 2>&1
echo "[growroot] growpart exit code=$?" > /dev/kmsg

# Grow filesystem
/sbin/resize2fs /dev/xvda2 > /dev/kmsg 2>&1
echo "[growroot] resize2fs exit code=$?" > /dev/kmsg
