-- PostgreSQL

CREATE TABLE iaas_storage_members (
    id                    bigint NOT NULL DEFAULT nextval('iaas_storage_members_id_seq'::regclass),
    uuid                  uuid DEFAULT gen_random_uuid(),
    name                  text NOT NULL,
    hostname              text,
    ip_addr               text,
    local_ip_addr         text,
    management_data       json,
    configuration_data    text,
    is_healthy            boolean DEFAULT true,
    has_warning           boolean DEFAULT false,
    has_error             boolean DEFAULT false,
    features              json,
    is_behind_firewall    boolean DEFAULT false,
    total_socket          integer NOT NULL DEFAULT 2,
    total_cpu             integer NOT NULL DEFAULT 16,
    total_ram             integer NOT NULL DEFAULT 128,
    total_disk            integer NOT NULL DEFAULT 1000,
    used_disk             integer NOT NULL DEFAULT 0,
    disk_info             json,
    uptime                timestamp with time zone,
    idle_time             timestamp with time zone,
    benchmark_score       integer DEFAULT 0,
    is_maintenance        boolean DEFAULT false,
    is_alive              boolean NOT NULL DEFAULT false,
    iaas_storage_pool_id  bigint,
    iam_account_id        bigint NOT NULL,
    iam_user_id           bigint NOT NULL,
    tags                  text[] NOT NULL DEFAULT '{}'::text[],
    created_at            timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at            timestamp with time zone,
    ssh_username          text,
    ssh_password          text,
    ssh_port              integer DEFAULT 22,
    CONSTRAINT iaas_storage_members_pkey PRIMARY KEY (id)
);
