-- PostgreSQL

CREATE TABLE iaas_repository_images (
    id                         bigint NOT NULL DEFAULT nextval('iaas_repository_images_id_seq'::regclass),
    uuid                       uuid DEFAULT gen_random_uuid(),
    name                       text NOT NULL,
    description                text,
    path                       text NOT NULL,
    filename                   text NOT NULL,
    default_username           text,
    default_password           text,
    is_active                  boolean DEFAULT true,
    is_iso                     boolean DEFAULT true,
    is_virtual_machine_image   boolean DEFAULT false,
    is_docker_image            boolean DEFAULT false,
    os                         text,
    distro                     text,
    version                    text,
    release_version            text,
    is_latest                  boolean DEFAULT false,
    extra                      text,
    cpu_type                   text,
    supported_virtualizations  text[],
    iaas_repository_id         bigint NOT NULL,
    hash                       text,
    iam_account_id             bigint NOT NULL,
    iam_user_id                bigint NOT NULL,
    created_at                 timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                 timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at                 timestamp with time zone,
    size                       integer, -- [label:"Size in Megabytes"]
    ram                        integer DEFAULT 1,
    cpu                        integer DEFAULT 2,
    is_public                  boolean NOT NULL DEFAULT true,
    iaas_virtual_machine_id    bigint,
    has_plusclouds_service     boolean DEFAULT false,
    is_cloudinit_image         boolean DEFAULT false,
    post_boot_script           text,
    CONSTRAINT iaas_repository_images_pkey PRIMARY KEY (id)
);
